# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 696bf35b6613492e2f8800a9185cbcf5311152fcd1da8c510ba4967aa847f7d0cf079f1daa120d51868c0680ee74c46568166bb9ff7df55e04098785b054d1e0

test:
  secret_key_base: 65e19f0fc7f8d30ad558cb52076147d22c8dc8abf964dc5652500f01b509d6157c1fe8dd980ad4d4555b360ba9eb8fbbf3da4f46dcc49b76c1ca4582766ad807

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
